services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - gao-yang_postgres_data_v1_partitioned:/var/lib/postgresql/data # Use named volume
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - gao_yang_network_v1_partitioned

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8090:80 # Access pgAdmin via http://localhost
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - gao_yang_network_v1_partitioned

volumes:
  gao-yang_postgres_data_v1_partitioned: {} # Named volume with default location

networks:
  gao_yang_network_v1_partitioned: {}
