name = "cloudflare-hono-d1"
main = "src/index.ts"
compatibility_date = "2024-11-29"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "vms-hono-d1"
database_id = "09b9dbbc-311d-4540-9865-e7f7b458a492"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1